name: Build and push

on:
  push:
    branches: [master]

jobs:
  deploy:
    uses: nevivurn/cd-test-config/.github/workflows/deploy-application.yaml@master
    with:
      app-name: cd-deployments
      app-id: 362932
      application: ${{ github.repository }}
      image: 'soomething'
      tag: '1240'
    secrets:
      app-secret: ${{ secrets.APP_SECRET }}
