on:
  push:
    branches: [master]

jobs:
  trigger:
    uses: nevivurn/cd-test-config/.github/workflows/app-token.yaml@master
    with:
      app-id: 362932
      application: ${{ github.repository }}
      image: 'soomething'
      tag: '1235'
    secrets:
      app-secret: ${{ secrets.APP_SECRET }}
